Multipart uploading
aiokitchen/aiohttp-s3-client pull request #1
Opened 2021-08-20 14:52 UTC by dizballanze

Docs are coming soon

2021-08-20 16:04 UTC, mosquito commented on aiohttp_s3_client/client.py
> +@threaded_iterable
max size should be set I guess

2021-08-21 07:50 UTC, alvassin requested changes

2021-08-21 07:50 UTC, alvassin commented on aiohttp_s3_client/client.py
> +        return await self.request("GET", object_name, **kwargs)
Юр, а как же "обязательно используйте async with, чтобы у вас не текли коннекты"?

2021-08-21 07:50 UTC, alvassin commented on aiohttp_s3_client/client.py
> +        return await self.request("GET", object_name, **kwargs)
https://github.com/aio-libs/aiobotocore/issues/738

2021-08-21 13:00 UTC, mosquito commented on aiohttp_s3_client/client.py
> +        return await self.request("GET", object_name, **kwargs)
Мы поэтому и возвращали без await, я вспомнил.

2021-08-22 11:12 UTC, dizballanze commented on aiohttp_s3_client/client.py
> +        return await self.request("GET", object_name, **kwargs)
Вообще release вызывается в `__del__`, но давайте явный вызов тоже добавлю

2021-08-23 07:50 UTC, alvassin approved these changes

2021-08-23 09:25 UTC, merged